name: ariang-windows

on:
  workflow_dispatch:

env:
  ver_nodejs_lts: "22.18.0"

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Node.js
        shell: pwsh
        run: |
          Invoke-WebRequest -Uri "https://nodejs.org/dist/v${{ env.ver_nodejs_lts }}/node-v${{ env.ver_nodejs_lts }}-x64.msi" -OutFile "nodejs.msi"; `
          msiexec /i nodejs.msi

      - name: Get source code
        shell: pwsh
        run: |
          git clone https://github.com/mayswind/AriaNg-Native.git ariang; `
          cd ariang; `
          $patches = Get-ChildItem "../ariang-native-patch" -Filter *.patch; `
          foreach ($patch in $patches) { `
            git apply $patch.FullName `
          };

      - name: Install
        shell: pwsh
        run: |
          cd ariang; `
          npm install;

      - name: Build
        shell: pwsh
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          cd ariang; `
          npm run publish:win;

      - name: Get filenames
        id: get_filenames
        shell: pwsh
        run: |
          "name_x64_7z=$((Get-ChildItem ariang/dist/AriaNg_Native-*-Windows-x64.7z).Name)" | Out-File -FilePath $env:GITHUB_OUTPUT -Append
          "name_x86_7z=$((Get-ChildItem ariang/dist/AriaNg_Native-*-Windows-x86.7z).Name)" | Out-File -FilePath $env:GITHUB_OUTPUT -Append
          "name_x64_exe=$((Get-ChildItem ariang/dist/AriaNg_Native-*-Windows-x64.exe).Name)" | Out-File -FilePath $env:GITHUB_OUTPUT -Append
          "name_x86_exe=$((Get-ChildItem ariang/dist/AriaNg_Native-*-Windows-x86.exe).Name)" | Out-File -FilePath $env:GITHUB_OUTPUT -Append

      - name: Upload artifact (x64 .7z)
        uses: actions/upload-artifact@v4
        with:
          name: ${{ steps.get_filenames.outputs.name_x64_7z }}
          path: ariang/dist/${{ steps.get_filenames.outputs.name_x64_7z }}

      - name: Upload artifact (x86 .7z)
        uses: actions/upload-artifact@v4
        with:
          name: ${{ steps.get_filenames.outputs.name_x86_7z }}
          path: ariang/dist/${{ steps.get_filenames.outputs.name_x86_7z }}

      - name: Upload artifact (x64 .exe)
        uses: actions/upload-artifact@v4
        with:
          name: ${{ steps.get_filenames.outputs.name_x64_exe }}
          path: ariang/dist/${{ steps.get_filenames.outputs.name_x64_exe }}

      - name: Upload artifact (x86 .exe)
        uses: actions/upload-artifact@v4
        with:
          name: ${{ steps.get_filenames.outputs.name_x86_exe }}
          path: ariang/dist/${{ steps.get_filenames.outputs.name_x86_exe }}

      - name: Make Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            ${{ steps.get_filenames.outputs.name_x64_7z }}
            ${{ steps.get_filenames.outputs.name_x86_7z }}
            ${{ steps.get_filenames.outputs.name_x64_exe }}
            ${{ steps.get_filenames.outputs.name_x86_exe }}
