name: aria2c-windows-x86_64-openssl

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          sparse-checkout: |
            aria2c-windows-x86_64-openssl.dockerfile
          sparse-checkout-cone-mode: false

      - name: Docker build
        run: docker build -t build_i - < aria2c-windows-x86_64-openssl.dockerfile

      - name: Fetch
        run: |
          docker run --name build_c build_i && \
          docker cp build_c:/build/aria2c.exe . && \
          docker cp build_c:/etc/ssl/certs/ca-certificates.crt .

      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: aria2c-windows-x86_64-openssl
          path: |
            ./aria2c.exe
            ./ca-certificates.crt
