name: ariang-windows-amd64

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-2022

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Node.js
        shell: pwsh
        run: |
          Invoke-WebRequest -Uri "https://nodejs.org/dist/v20.3.0/node-v20.3.0-x64.msi" -OutFile "nodejs.msi"; `
          msiexec /i nodejs.msi

      - name: Get source code
        shell: pwsh
        run: |
          git clone https://github.com/mayswind/AriaNg-Native.git ariang; `
          cd ariang; `
          $patches = Get-ChildItem "../ariang-native-patch" -Filter *.patch; `
          foreach ($patch in $patches) { `
            git apply $patch.FullName `
          };

      - name: Install
        shell: pwsh
        run: |
          cd ariang; `
          npm install;

      - name: Build
        shell: pwsh
        run: |
          cd ariang; `
          npm run publish:win;

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: AriaNg_Native-windows-x64.7z
          path: ariang/dist/AriaNg_Native-?.?.?-Windows-x64.7z

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: AriaNg_Native-windows-x86.7z
          path: ariang/dist/AriaNg_Native-?.?.?-Windows-x86.7z

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: AriaNg_Native-windows-x64.exe
          path: ariang/dist/AriaNg_Native-?.?.?-Windows-x64.exe

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: AriaNg_Native-windows-x86.exe
          path: ariang/dist/AriaNg_Native-?.?.?-Windows-x86.exe
