name: build-ariang-actions

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-2022

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Node.js
        shell: pwsh
        run: |
          Invoke-WebRequest -Uri "https://nodejs.org/dist/v17.3.1/node-v17.3.1-x64.msi" -OutFile "nodejs.msi"; `
          msiexec /i nodejs.msi

      - name: Get source code
        shell: pwsh
        run: |
          git clone https://github.com/mayswind/AriaNg-Native.git ariang; `
          cd ariang; `
          $patches = Get-ChildItem "../ariang-native-patch" -Filter *.patch; `
          foreach ($patch in $patches) { `
            git apply $patch.FullName `
          }; `

      - name: Build ariang
        shell: pwsh
        run: |
          cd ariang; `
          npm install; `
          npm run publish:win

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: AriaNg Native-win.7z
          path: ariang/dist/AriaNg Native-?.?.?-win.7z

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: AriaNg Native-ia32-win.7z
          path: ariang/dist/AriaNg Native-?.?.?-ia32-win.7z

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: AriaNg Native.msi
          path: ariang/dist/AriaNg Native ?.?.?.msi

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: AriaNg Native-ia32.msi
          path: ariang/dist/AriaNg Native ?.?.? ia32.msi
