name: build

on:
  workflow_dispatch:

jobs:
  build-windows:
    runs-on: ubuntu-20.04

    strategy:
      fail-fast: false
      matrix:
        platform: [x86_64-w64-mingw32, i686-w64-mingw32]

    env:
      HOST: ${{ matrix.platform }}
      DEBIAN_FRONTEND: noninteractive

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Linux setup
        run: |
          sudo apt-get update && \
            sudo apt-get install -y --no-install-recommends \
              make \
              binutils \
              autoconf \
              automake \
              autotools-dev \
              libtool \
              patch \
              ca-certificates \
              pkg-config \
              git \
              curl \
              dpkg-dev \
              gcc-mingw-w64 \
              g++-mingw-w64 \
              autopoint \
              libcppunit-dev \
              libxml2-dev \
              libgcrypt20-dev \
              lzip

      - name: Pull source codes
        run: |
          curl -L -O https://gmplib.org/download/gmp/gmp-6.2.1.tar.lz && \
            curl -L -O https://github.com/libexpat/libexpat/releases/download/R_2_4_1/expat-2.4.1.tar.bz2 && \
            curl -L -O https://www.sqlite.org/2021/sqlite-autoconf-3360000.tar.gz && \
            curl -L -O http://zlib.net/zlib-1.2.11.tar.gz && \
            curl -L -O https://c-ares.haxx.se/download/c-ares-1.17.2.tar.gz && \
            curl -L -O https://www.libssh2.org/download/libssh2-1.9.0.tar.gz && \
            curl -L -O https://github.com/libssh2/libssh2/commit/ba149e804ef653cc05ed9803dfc94519ce9328f7.patch

      - name: Build gmp
        run: |
          tar xf gmp-6.2.1.tar.lz && \
            cd gmp-6.2.1 && \
            ./configure \
                --disable-shared \
                --enable-static \
                --prefix=/usr/local/$HOST \
                --host=$HOST \
                --disable-cxx \
                --enable-fat \
                CFLAGS="-mtune=generic -O2 -g0" && \
            sudo make install

      - name: Build expat
        run: |
          tar xf expat-2.4.1.tar.bz2 && \
            cd expat-2.4.1 && \
            ./configure \
                --disable-shared \
                --enable-static \
                --prefix=/usr/local/$HOST \
                --host=$HOST \
                --build=`dpkg-architecture -qDEB_BUILD_GNU_TYPE` && \
            sudo make install

      - name: Build sqlite
        run: |
          tar xf sqlite-autoconf-3360000.tar.gz && \
            cd sqlite-autoconf-3360000 && \
            ./configure \
                --disable-shared \
                --enable-static \
                --prefix=/usr/local/$HOST \
                --host=$HOST \
                --build=`dpkg-architecture -qDEB_BUILD_GNU_TYPE` && \
            sudo make install

      - name: Build zlib
        run: |
          tar xf zlib-1.2.11.tar.gz && \
            cd zlib-1.2.11 && \
            CC=$HOST-gcc \
            AR=$HOST-ar \
            LD=$HOST-ld \
            RANLIB=$HOST-ranlib \
            STRIP=$HOST-strip \
            ./configure \
                --prefix=/usr/local/$HOST \
                --libdir=/usr/local/$HOST/lib \
                --includedir=/usr/local/$HOST/include \
                --static && \
            sudo make install

      - name: Build c-ares
        run: |
          tar xf c-ares-1.17.2.tar.gz && \
            cd c-ares-1.17.2 && \
            ./configure \
                --disable-shared \
                --enable-static \
                --without-random \
                --prefix=/usr/local/$HOST \
                --host=$HOST \
                --build=`dpkg-architecture -qDEB_BUILD_GNU_TYPE` \
                LIBS="-lws2_32" && \
            sudo make install

      - name: Build libssh2
        run: |
          tar xf libssh2-1.9.0.tar.gz && \
            cd libssh2-1.9.0 && \
            patch -p1 < ../ba149e804ef653cc05ed9803dfc94519ce9328f7.patch && \
            ./configure \
                --disable-shared \
                --enable-static \
                --prefix=/usr/local/$HOST \
                --host=$HOST \
                --build=`dpkg-architecture -qDEB_BUILD_GNU_TYPE` \
                --without-openssl \
                --with-wincng \
                LIBS="-lws2_32" && \
            sudo make install

      - name: Build aria2
        run: |
          git clone https://github.com/aria2/aria2 && \
            cd aria2 && \
            git apply ../aria2-patch/*.patch && \
            autoreconf -i && \
            ./mingw-config && \
            make && \
            $HOST-strip src/aria2c.exe

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: aria2-${{ matrix.platform }}
          path: aria2/src/aria2c.exe

  build-linux-amd64:
    runs-on: ubuntu-20.04

    env:
      PREFIX: "build-deps"
      CURL_CA_BUNDLE: "/etc/ssl/certs/ca-certificates.crt"
      PKG_CONFIG_PATH: "$PREFIX/lib/pkgconfig"
      LD_LIBRARY_PATH: "$PREFIX/lib"
      CC: "gcc"
      CXX: "g++"
      RANLIB: "ranlib"
      AR: "ar"
      LD: "ld"
      DEBIAN_FRONTEND: noninteractive
      ZLIB: 'https://www.zlib.net/zlib-1.2.11.tar.gz'
      EXPAT: 'https://github.com/libexpat/libexpat/releases/download/R_2_4_1/expat-2.4.1.tar.bz2'
      C_ARES: 'https://c-ares.haxx.se/download/c-ares-1.17.2.tar.gz'
      OPENSSL: 'https://www.openssl.org/source/openssl-1.1.1k.tar.gz'
      SQLITE3: 'https://www.sqlite.org/2021/sqlite-autoconf-3360000.tar.gz'
      LIBSSH2: 'https://www.libssh2.org/download/libssh2-1.9.0.tar.gz'
      JEMALLOC: 'https://github.com/jemalloc/jemalloc/releases/download/5.2.1/jemalloc-5.2.1.tar.bz2'

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Linux setup
        run: |
          sudo apt-get update && \
            sudo apt-get install -y --no-install-recommends \
              build-essential \
              git \
              curl \
              ca-certificates \
              libxml2-dev \
              libcppunit-dev \
              autoconf \
              automake \
              autotools-dev \
              autopoint \
              libtool \
              pkg-config

      - name: Build zlib
        run: |
          mkdir -p "zlib" && \
          cd "zlib" && \
          curl -Ls -o - "$ZLIB" | tar zxvf - --strip-components=1 && \
          ./configure \
              --prefix=$PREFIX \
              --static && \
          make -j$(nproc) && \
          sudo make install

      - name: Build expat
        run: |
          mkdir -p "expat" && \
          cd "expat" && \
          curl -Ls -o - "$EXPAT" | tar jxvf - --strip-components=1 && \
          ./configure \
              --prefix=$PREFIX \
              --enable-static \
              --disable-shared \
              --without-examples \
              --without-tests \
              --without-docbook && \
          make -j$(nproc) && \
          sudo make install

      - name: Build c-ares
        run: |
          mkdir -p "c-ares" && \
          cd "c-ares" && \
          curl -Ls -o - "$C_ARES" | tar zxvf - --strip-components=1 && \
          ./configure \
              --prefix=$PREFIX \
              --enable-static \
              --disable-shared \
              --disable-tests && \
          make -j$(nproc) && \
          sudo make install

      - name: Build openssl
        run: |
          mkdir -p "openssl" && \
          cd "openssl" && \
          curl -Ls -o - "$OPENSSL" | tar zxvf - --strip-components=1 && \
          ./Configure \
              --prefix=$PREFIX \
              "linux-x86_64" \
              no-tests && \
          make -j$(nproc) && \
          sudo make install_sw

      - name: Build sqlite3
        run: |
          mkdir -p "sqlite3" && \
          cd "sqlite3" && \
          curl -Ls -o - "$SQLITE3" | tar zxvf - --strip-components=1 && \
          ./configure \
              --prefix=$PREFIX \
              --enable-static \
              --disable-shared \
              --disable-dynamic-extensions && \
          make -j$(nproc) && \
          sudo make install

      - name: Build libssh2
        run: |
          mkdir -p "libssh2" && \
          cd "libssh2" && \
          curl -Ls -o - "$LIBSSH2" | tar zxvf - --strip-components=1 && \
          ./configure \
              --prefix=$PREFIX \
              --enable-static \
              --disable-shared \
              --disable-examples-build && \
          make -j$(nproc) && \
          sudo make install

      - name: Build aria2
        run: |
          git clone https://github.com/aria2/aria2 && \
            cd aria2 && \
            git apply ../aria2-patch/*.patch && \
            autoreconf -fi || autoreconf -fiv && \
            ./configure \
                --prefix='/usr/loacl' \
                --with-libz \
                --with-libcares \
                --with-libexpat \
                --without-libxml2 \
                --without-libgcrypt \
                --with-openssl \
                --without-libnettle \
                --without-gnutls \
                --without-libgmp \
                --with-libssh2 \
                --with-sqlite3 \
                --without-jemalloc \
                --with-ca-bundle='/etc/ssl/certs/ca-certificates.crt' \
                ARIA2_STATIC=yes \
                --disable-shared && \
            make -j$(nproc) && \
            strip src/aria2c

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: aria2-static-linux-amd64
          path: aria2/src/aria2c
