name: build-aria2c-linux-docker

on:
  workflow_dispatch:

jobs:
  build-linux-amd64:
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Docker build
        run: docker build -t aria2-build - < aria2-gnu-linux-build-amd64.dockerfile

      - name: Extract
        run: |
          id=$(docker create aria2-build) && \
          docker cp $id:/build/aria2c .

      - name: Test
        run: |
          ./aria2c https://raw.githubusercontent.com/P3TERX/aria2.conf/master/dht.dat && \
          ./aria2c https://raw.githubusercontent.com/P3TERX/aria2.conf/master/dht6.dat && \
          ./aria2c \
            --seed-time=0 \
            --enable-dht6=true \
            --dht-file-path="$PWD/dht.dat" \
            --dht-file-path6="$PWD/dht6.dat" \
            --dht-entry-point='dht.transmissionbt.com:6881' \
            --dht-entry-point6='dht.transmissionbt.com:6881' \
            "$(curl -fsSL https://ubuntu.com/download/alternative-downloads | grep -o 'https.*server.*torrent' | head -1)"

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: aria2-static-linux-amd64
          path: ./aria2c
